"""forgot body column

Revision ID: fd2db8bf6e5e
Revises: af3ba0a5e44f
Create Date: 2023-05-24 01:18:34.008248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd2db8bf6e5e'
down_revision = 'af3ba0a5e44f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('body')

    # ### end Alembic commands ###
